test/test.yml, txpipe/selector.py, txpipe/twopoint.py
This pull request addresses changes to twopoint.py to output in SACC format and include metadata with sigma_e and n_eff. Any comments and suggestions on the changes are greatly appreciated.
=> Numdens stats

test/test-fourier.yml, test/test-real.yml, test/test-small.yml, test/test-small.yml~, txpipe/covariance.py, txpipe/data_types/types.py, txpipe/photoz_stack.py, txpipe/twopoint.py, txpipe/twopoint_fourier.py
PR to address the output formats from TXPipe into FireCrown.
=> Cov Outputs

txpipe/metacal_gcr_input.py
Updating this input cat with the fields available from `dc2_object_run1.2i_tract5063_with_metacal.yaml`
As per your request, I'm now saving g1 and g2 in two separate fields
=> Fixes metacal columns

txpipe/photoz_stack.py
Save the 2D n(z) as well as the tomographic bins.  It saves to a new group called source2d.
=> save 2d n(z)

txpipe/twopoint_fourier.py
Fixes UNSEEN pixels being included in namaster spectra.
Also use namaster helper function to simplify.
=> 2pt mask fix

examples/2.2i-t3828.yml, txpipe/diagnostics.py, txpipe/selector.py, txpipe/utils/fitting.py, txpipe/utils/metacal.py, txpipe/utils/number_density_stats.py
Add and use a generic Calibrator object for Metacal, that collects the estimator and selection responses and sums them together for any given selection function.
Also use this to make a MeanShearInBins class
=> Calibrator object

txpipe/sysmaps.py, txpipe/utils/theory.py
Tool to generate fake maps for testing Fourier code
=> Add fake map tool and theory support file

examples/config.yml, txpipe/photoz_stack.py
This new stage gets the truth values of the n(z) if they are found in the catalog.
=> TXTrueNumberDensity

examples/config.yml, txpipe/input_cats.py, txpipe/mapping/basic_maps.py, txpipe/metacal_gcr_input.py, txpipe/sysmaps.py
This saves the count of the number of objects in the lensing maps as a lensing weight map for later.
Update: now saves a summed weight, though this is the same is the count in our case.
=> Save lensing weight map in sys maps

examples/config.yml, txpipe/covariance.py, txpipe/twopoint.py
=> Jackknife - residual changes

txpipe/source_selector.py
Small bug when using `input_pz = True`
=> Fixed small bug

examples/config/cosmodc2_config.yml, examples/cosmodc2_redmagic_pipeline.yml, txpipe/lens_selector.py, txpipe/plotting/correlations.py, txpipe/twopoint.py
Fixing config file to run through with cosmodc2 and adding feature to run without shape noise.
=> No shape noise

txpipe/diagnostics.py, txpipe/twopoint.py, txpipe/utils/calibration_tools.py
This implements the HSC shear calibration. I've also added a new catalog type 'hsc', that uses the new calibration.
=> Implemented HSC shear calibration and added new hsc catalog type.

txpipe/diagnostics.py, txpipe/maps.py, txpipe/test/test_main.py
Bug fixes found as part of the dr6c analysis
=> Fixes to mapping and diagnostics

examples/config/laptop_config.yml, examples/config/laptop_lensfit_config.yml, txpipe/diagnostics.py, txpipe/metadata.py, txpipe/source_selector.py, txpipe/twopoint.py, txpipe/utils/number_density_stats.py
This is a small pull request to
1) calculate the mean shear in each tomographic bin and store this in the metadata hdf and yml file 
2) add an option to twopoint to subtract this value
=> Mean shear

txpipe/lens_selector_hsc.py, txpipe/source_selector_hsc.py
This adds two HSC-specific selection scripts for sources and lenses and applies only the i_band magnitude cut as in the HSC paper.
=> Added HSC-specific selection scripts.

examples/config/dr1b_config.yml, examples/dr1b_pipeline.yml, txpipe/twopoint_fourier.py
Added systematics deprojection for galaxy number counts in TXTwoPointFourier.
See https://github.com/LSSTDESC/TXPipe/issues/98.
=> Systematics deprojection

README.md, examples/2.2i_pipeline.yml, examples/cori-2.2i.sub
Adds a cori batch script example
=> add cori batch example

txpipe/covariance.py, txpipe/data_types/base.py, txpipe/data_types/types.py, txpipe/metadata.py, txpipe/twopoint.py, txpipe/twopoint_fourier.py
- Adds and uses a FiducialCosmology data type subclass
- Adds helper methods including metadata to YamlFile
- Removes some stray commas in metadata that were making things get saved as tuples
=> Change how YAML is saved/loaded

examples/config/cosmodc2_config.yml, examples/config/cosmodc2_config_no_shape_noise.yml, txpipe/maps.py, txpipe/twopoint_fourier.py
Adding options when need to obtain a Fourier space measurement on cosmodc2 without shape noise and corresponding covariance.
=> No noise fourier

txpipe/twopoint_fourier.py
Added deprojection for shear. Uses all maps in specified directory. If map file name contains "_e1","e_2" assumes it is a pair. If not, assumes it is a scalar map.
=> added wl deprojection

txpipe/twopoint_fourier.py
Removed comments from some calculations.
=> uncomment calcs

examples/laptop_pipeline.yml, txpipe/rail_pz.py
This adds a post-RAIL calculation of the mean redshift of each galaxy.
=> Restore mean z in rail estimate

data/fiducial_cosmology.yml, examples/config/cosmodc2_config.yml, examples/config/cosmodc2_config_no_shape_noise.yml, examples/config/laptop_config.yml, examples/config/laptop_flat_sky_maps.yml, examples/config/laptop_lensfit_config.yml, examples/cosmodc2_redmagic_pipeline_no_shape_noise.yml, examples/cosmodc2_redmagic_pipeline_no_shape_noise_full.yml, txpipe/input_cats.py, txpipe/photoz_stack.py, txpipe/twopoint.py, txpipe/utils/calibration_tools.py
Adapt `TXCosmoDC2Mock` stage to cut sources in magnitude, instead of snr.
=> Cosmodc2 magcut

requirements.txt
=> pin xgboost

txpipe/test/test_cal.py, txpipe/utils/calibrators.py
This should fix the issue Judit has seen, #186
=> Fix for issue #186

txpipe/random_cats.py, txpipe/source_selector.py, txpipe/twopoint_null_tests.py
This removes some left over inputs that are never used in three stages.
=> remove some inputs that are never used

txpipe/theory.py
Fix bug that was not computing the theory predictions for wtheta cross-correlations.
=> Fix bug that was not computing the theory predictions for wtheta 

txpipe/__init__.py, txpipe/cosmos_weight.py, txpipe/data_types/types.py, txpipe/lens_selector_hsc.py, txpipe/photoz_dir.py
This PR adds two pipeline stages: `TXCOSMOSWeight` and `TXPhotozDIR` that implement estimation of photoz distributions using DIR from COSMOS 30 band data ([https://ui.adsabs.harvard.edu/abs/2016ApJS..224...24L/abstract]).
=> Photoz DIR

examples/config/bpz_riz.columns, examples/config/bpz_ugrizy.columns, examples/config/laptop_config.yml, examples/config/laptop_lensfit_config.yml, examples/laptop_pipeline.yml, requirements.txt, txpipe/rail/estimate.py, txpipe/rail/utils.py
This will switch the RAIL algorithm used in the continuous integration for the faster BPZ one.
=> Switch CI to use RAIL BPZ algorithm

examples/config/cosmodc2_config.yml, txpipe/covariance.py
Before galaxy_bias = 1 was hard-coded. This pull request allows to input the galaxy bias values the user wants in the config file.
=> Adding variable for galaxy bias in covariance

examples/cosmodc2/config.yml, examples/cosmodc2/pipeline_redmagic.yml, txpipe/auxiliary_maps.py, txpipe/data_types/types.py, txpipe/mapping/basic_maps.py, txpipe/maps.py, txpipe/masks.py, txpipe/metadata.py, txpipe/noise_maps.py, txpipe/test/test_mapper.py, txpipe/twopoint_fourier.py
Add functionality to compute `cl_noise` in `twopoint_fourier` from analytic function, to compare with the one obtained from the maps as a validation. Most of the code is copied from HSC branch, but some of the code has been modified to fix two bugs.
=> Fix fourier

txpipe/covariance.py, txpipe/twopoint_fourier.py, txpipe/utils/nmt_utils.py
I have merged the tjpcov-related files from master to the HSC branch.
=> Update HSC branch to compute covariances with TJPCov

examples/2.2i/pipeline.yml, examples/2.2i/pipeline_1tract.yml, examples/cosmodc2/pipeline.yml, examples/dr1b/pipeline.yml, examples/gaussian_sims/config.yml, examples/gaussian_sims/pipeline_gaussian_sims.yml, examples/gaussian_sims/pipeline_gaussian_sims_inputcats.yml, examples/metacal/pipeline.yml, examples/metadetect/pipeline.yml, examples/skysim/pipeline.yml, txpipe/__init__.py, txpipe/auxiliary_maps.py, txpipe/calibrate.py, txpipe/covariance.py, txpipe/data_types/types.py, txpipe/input_cats.py, txpipe/map_plots.py, txpipe/maps.py, txpipe/noise_maps.py, txpipe/source_selector.py, txpipe/theory.py, txpipe/twopoint_fourier.py, txpipe/utils/theory.py
Changes to be able to run through some simpler simulation.
=> Gaussian sims

examples/gaussian_sims/config.yml, examples/gaussian_sims/pipeline_gaussian_sims.yml, txpipe/twopoint_fourier.py
More bug fixes, improvements and config setting changes to run through the Gaussian simulations with LSST Y1 like settings.
=> Run gaussian sims3

txpipe/calibrate.py, txpipe/data_types/types.py, txpipe/source_selector.py, txpipe/utils/calibration_tools.py
There's a typo in the latest version, in a calibrate - this PR is a fix.
=> Fix cal typo.

examples/cosmodc2/config.yml, examples/cosmodc2/pipeline_redmagic_full.yml, examples/gaussian_sims/config.yml, examples/gaussian_sims/pipeline_gaussian_sims.yml, txpipe/covariance.py, txpipe/source_selector.py, txpipe/theory.py, txpipe/twopoint.py, txpipe/twopoint_fourier.py, txpipe/utils/theory.py
This pull request includes:
- Implementation of pixel-based estimator for real space twopoint stage. (only for clustering now)
- Remove try, excepts for CCL error handling.
- Updating pipeline and config files.
=> Gaussian sims run5

.github/workflows/ci.yml, examples/randoms/config_randomsonly.yml, examples/randoms/pipeline_randomsonly.yml, requirements.txt, txpipe/random_cats.py
Added option to generate randoms using ntessore/healpix package (https://github.com/ntessore/healpix)
Faster than generating per pixel from quadrilateral (~0.3min vs 10min on one core) and will maintain matching to healpix pixel ids when using healpy tools
=> Tessore randoms

README.md, environment.yml
See the PR #322 which has a new issue with JAX.
=> Trying to fix jax problem in installer

examples/desy1/pipeline.yml, txpipe/source_selector.py, txpipe/test/test_cal.py, txpipe/test/test_cal_hsc.py, txpipe/test/test_cal_lensfit.py, txpipe/utils/calibration_tools.py, txpipe/utils/nmt_utils.py
Fix to make Neff  (computed from weights) passed to BinStats instead of raw counts (direct sum of number of objects).
=> Fix counts

txpipe/theory.py
=> Fix order of arguments in theory.py function call

txpipe/diagnostics.py
adding new diagnostic plot that looks at mean galaxy shear vs band magnitude
=> mean shear vs mag

examples/ext_cross_corr/config_1deg.yml, examples/ext_cross_corr/pipeline_1deg.yml, txpipe/twopoint.py
Add stage to compute two-point between external healsparse maps (e.g. survey properties or dust maps) and TXPipe tracers: Galaxy density and Shear
=> Ext cross corr

txpipe/twopoint.py
fixed small bug in twopoint stage when using auto correlation and subsampled randoms
=> fixed bug in auto correlation when using subsampled randoms

examples/ssi/config_gcr.yml, examples/ssi/config_mag.yml, examples/ssi/pipeline_gcr.yml, examples/ssi/pipeline_mag.yml, txpipe/__init__.py, txpipe/ingest/__init__.py, txpipe/ingest/ssi.py, txpipe/injection.py, txpipe/magnification.py
- Added stage to ingest SSI inputs 
- Added stage to compute magnification signal from SSI catalogs
=> SSI SRV inputs

environment-nopip.yml, environment-piponly.yml
Changes to make it easier to build for shifter at NERSC in https://github.com/LSSTDESC/txpipe-docker
=> Shifter mpi fix

.github/workflows/ci.yml, bin/install.sh, bin/make_output_report.py, environment-nopip.yml, examples/metadetect_source_only/pipeline.yml
This updates the CI to drop the docker tests, put all the tests under one matrix job, and save a PDF artifact of all the plots made.
=> Updating CI

docs/make-stages.py, docs/minimal-requirements.txt, docs/src/conf.py, docs/src/stages/Blinding.rst, docs/src/stages/Calibration and Splitting.rst, docs/src/stages/Covariance.rst, docs/src/stages/Diagnostics.rst, docs/src/stages/Ensemble Photo-z.rst, docs/src/stages/Extensions.rst, docs/src/stages/Ingestion.rst, docs/src/stages/Maps.rst, docs/src/stages/New and Miscellaneous.rst, docs/src/stages/Photo-z.rst, docs/src/stages/Plots.rst, docs/src/stages/Selection.rst, docs/src/stages/Source Injection.rst, docs/src/stages/Two-Point.rst, docs/src/stages/Weights.rst
This changes how the docstrings are generated for the new ceci format.
=> Documentation update for ceci 2.2
