LSSTDESC/TXPipe

.gitignore, test/config.yml, test/setup-cori, txpipe/photoz.py, txpipe/selector.py, txpipe/sysmaps.py
Minor update to make TXPipe compatible with new Ceci convention on config_options without default values. This is compatible with https://github.com/LSSTDESC/ceci/tree/cwl and related to https://github.com/LSSTDESC/ceci/pull/2
It's just a matter of replacing config_options without defaults to the expected type, instead of just None e.g.:
```
-    config_options = {'T_cut':None, 's2n_cut':None, 'delta_gamma': None, 'max_rows':0, 'chunk_rows':10000, 'zbin_edges':None}
+    config_options = {'T_cut':float, 's2n_cut':float, 'delta_gamma': float, 'max_rows':0,
+                      'chunk_rows':10000, 'zbin_edges':[float]}
```
Should only be merged if and when https://github.com/LSSTDESC/ceci/pull/2 gets merged
=> Ceci update

examples/config.yml, txpipe/selector.py
In selector.py add the option to use an input redshift point-estimate for each galaxy to do the binning. This is determined by the parameter `input_pz`  set in the configuration file. `input_pz: False` will give the original pipeline. 
- requires a pre-existing photoz_stack.hdf5 file 
- skip "PZPDFMLZ" and "TXPhotozStack" stages if `input_pz: True`
Example for DES Y1 is described [here](https://github.com/LSSTDESC/txpipe-reanalysis/issues/6). Other experiments will do this differently since they do not have metacal photo-z's. Yaml and config files [here](https://github.com/LSSTDESC/txpipe-reanalysis/blob/master/desy1/desy1_input_pz.yml) and [here](https://github.com/LSSTDESC/txpipe-reanalysis/blob/master/desy1/config_input_pz.yml).
=> Add option to use input pz instead of running MLZ

txpipe/__init__.py, txpipe/input_cats.py
- Renames to CosmoDC2Mock and uses that catalog (instead of Proto) by default
- Updates GCR calls
- Add unit_response option to make all metacal R values either 1 (for shear R11 and R22) or 0 (everything else) 
- Adds flip_g2 option to make convention match treecorr and NaMaster
- Speed up
- Fix bug giving wrong SNR values for variants, affecting selection corrections
- Remove old code
=> Updated ingestion

txpipe/base_stage.py, txpipe/utils/provenance.py
Avoid crashes in provenance tracking when on very slow file systems or when encountering other git problems, or missing provenance in the input data files.
Addresses #84
=> Provenance fixes

txpipe/ingest_redmagic.py, txpipe/lens_selector.py
This is to support later use of lens weights.  Currently these are not used, but in a subsequent PR they will be.
=> Generate a new lens_weight column on ingest/select.  Not yet used

examples/buzzard_input_pipeline.yml, examples/config/buzzard_config.yml, txpipe/input_cats.py
This small PR simply adds the option to create some mock metacal input data out of Buzzard
NOTE: That I couldn't excatly manage to run it for more than one healpix pixel, I'm not sure how @joezuntz does it for CosmoDC2. 
Also I've had to comment out this line:
https://github.com/LSSTDESC/TXPipe/blob/1023b100176205c01ae41e9acb7fcfd9c4883d18/txpipe/input_cats.py#L342
It was failing and I couldn't understand why it was there....
=> Adds support for buzzard as input mock catalog

examples/config/cosmodc2_config.yml, txpipe/covariance.py
Adding an option in the Covariance stage to set sigma_e to zero when running without shape noise, to get a consistent gaussian covariance.
=> No shape noise

txpipe/metadata.py
This saves R_scalar (which is per-bin) instead of R (which is per object) to the metadata files.
I think R_scalar should be all that's needed.
=> modify metadata to copy R_mean instead of R

txpipe/ingest_redmagic.py, txpipe/lens_selector.py, txpipe/mapping/basic_maps.py, txpipe/maps.py, txpipe/metadata.py, txpipe/source_selector.py, txpipe/utils/number_density_stats.py
This change adds non-tomographic source and lens bins, for example for correlating with systematics.
It:
- adds the counts to the number density stats (simple)
- saves them in the lens selector (simple)
- (added) add 2d counts in redmagic ingest
- makes and calibrates the 2D source map (medium)
- adds a new 2D calibrator for the source selector, reorganizing the selection to avoid copy-paste selections (fiddly)
- reorganizes metadata output slightly (bit fiddly)
=> Add 2D (non-tomographic) lens and calibrated source bins

examples/config/cosmodc2_config.yml, txpipe/twopoint_fourier.py, txpipe/utils/nmt_utils.py
Adding the following features:
- Possibility to easily change the ell binning. Added the following options in the config file in `twopoint_fourier.py`:
"ell_min": 100,
"ell_max": 1500,
"n_ell": 20,
"ell_spacing": 'log'
- Switched the plotting script to load `summary_statistics_fourier.sacc` instead of `twopoint_data_fourier.sacc` to include errorbars in the plots (the covariance is now in the `summary_statistics_fourier.sacc` file).
=> Ell binning and plots

txpipe/twopoint.py
Addresses issue #156 by moving the flip from `load_shear_catalog` to `get_calibrated_catalog_bin`.
=> flip g2 right at the end

txpipe/ingest_redmagic.py
Currently the redmagic ingestion phases uses the redmagic estimated n(z) for both binning and to generate the estimated n(z).  This switches it to use the truth n(z) for the latter so we get less sharp bin edges.
=> Change redmagic ingest to make true n(z) stack

.github/workflows/python-package.yml, examples/2.2i_single_tract_pipeline.yml, txpipe/test/test_cal.py, txpipe/utils/calibration_tools.py
Addresses issue #165, adding weights to the selection bias calibration.
At the same time it simplifies the R_gamma (estimator) part of the calibration by using the ParallelMean tool.
The old version was also slightly wrong, since it did the weighted mean of the differences, instead of the diff of the weighted mean, which is not (quite) the same.
=> Add weights to metacal selection bias calculation and tidy R_gamma part

txpipe/source_selector.py
Previously objects of any redshift went into the 2D bin.
This change makes it so that only objects that fall into any of the other redshift bins do so.  This makes it so that e.g. the 2D sample is the combination of all the other tomo bins.
=> Fix selection of 2D objects to include only things in any WL bin

examples/2.2i_pipeline.yml, examples/2.2i_single_tract_pipeline.yml, examples/config/2.2i_config.yml, examples/config/cosmodc2_config.yml, examples/config/cosmodc2_config_no_shape_noise.yml, examples/config/dr1b_config.yml, examples/config/laptop_config.yml, examples/config/laptop_flat_sky_maps.yml, examples/config/laptop_lensfit_config.yml, examples/config/skysim5000_config.yml, examples/cosmodc2_pipeline.yml, examples/cosmodc2_redmagic_pipeline.yml, examples/cosmodc2_redmagic_pipeline_no_shape_noise.yml, examples/cosmodc2_redmagic_pipeline_no_shape_noise_full.yml, examples/dr1b_pipeline.yml, examples/laptop_complete_pipeline.yml, examples/laptop_lensfit_pipeline.yml, examples/laptop_pipeline.yml, examples/laptop_redmagic_complete_pipeline.yml, examples/laptop_redmagic_pipeline.yml, examples/skysim5000_pipeline.yml, txpipe/__init__.py, txpipe/auxiliary_maps.py, txpipe/diagnostics.py, txpipe/map_plots.py, txpipe/maps.py, txpipe/masks.py, txpipe/noise_maps.py, txpipe/random_cats.py
The previous implementation of the mapping code assumed in some places that the photometry and shear catalogs were the same length; this won't be the case for metadetect and other catalogs.
The main map-making code already had optional separate lens and source mappers.
This PR:
- errors with a useful message if the user tries to use a combined mapper when the lengths are different
- split the auxiliary maps into aux_source_maps (PSF and flag maps) and aux_lens_maps (bright object and depth maps), with a stage to make each
- updates the downstream uses of the aux maps to use the right one(s)
- updates yaml pipeline and config files
Most of the changes are to configuration files and pipeline yaml, switching them to use the new stages; if you're reviewing this they don't really need to be …
=> Stop assuming photometry and shear catalogs are the same size in map code

txpipe/covariance.py
In the old code the xip covariance was being computed twice, instead of computing once the xip and then the xim covariance. This pull request aims to fixing this.
=> Fixing bug in the real space covariance 

txpipe/twopoint.py
Fixes problem Judit sees with clashing cache dirs
=> For unknown files in TXTwoPoint make cache dir based on creation time and absolute path

txpipe/covariance.py
Allow computing the NaMaster covariance's blocks in parallel. It will be fully functional after merging this PR: https://github.com/LSSTDESC/TJPCov/pull/29
=> TJPCov NaMaster covariance parallelized

txpipe/covariance.py, txpipe/twopoint_fourier.py
Instead of recomputing the noise in TJPCov, we pass the noise computed already by TXPipe. 
I have also fixed:
- an error introduced in previous update: I had removed the possibility of using ell_edges for the binning. Now it can be used again as it was. Note that in the way that is (and was) implemented, your last ell_edge must be 3 * nside for the covariance to be computed. 
- the shear analytical noise: Nell = 0 for ell = 1, 2 now
=> Update HSC branch to use already computed noise in TJPCov

txpipe/covariance.py, txpipe/twopoint_fourier.py
I have done the following:
-  Store the noise and coupled noise in the `twopoint_fourier.fits` file. The noise as a tag in each of the data points (copied from the HSC branch) and the coupled noise as a metadata of the tracers. This assumes the coupled noise to be constant and might be necessary to be changed in the future.
- Fix the analytic noise computation. The expressions used give directly the coupled noise not the decoupled. I haven't checked the actual calculation, just assumed it was OK and interpret it as a coupled noise, instead of decouple. I think @damonge agrees with this. @jpratmarti it'd be great if you could have a look at this, since you've been working on it before.
=> Use computed coupled noise in TXTwoPointFourier to compute covariance with TJPCov

README.md
During the txpipe tutorial today I noticed the link to the ReadTheDocs page was broken in the main README. I think this fixes it.
=> Fix readthedocs link in README

bin/metacal_to_metadet.py, examples/star-challenge/config.yml, examples/star-challenge/sample-for-pz.yml, txpipe/binning/__init__.py, txpipe/binning/random_forest.py, txpipe/calibrate.py, txpipe/lens_selector.py, txpipe/photoz_stack.py, txpipe/source_selector.py
This adds a pipeline to generate nicer files for the PZ group to start testing with, and some supporting code.
- A script to make a metacal file into a metadetect one, so I can reuse some old files instead of re-ingesting
- The pipeline YML files
- Moves the random forest binning so it can be used by both source and lens
- Adds a lensing tomography code using the random forest
- Allows saving extra columns in the stages that split the catalogs into bins
=> Star challenge: Nicer binned files for PZ to use

txpipe/twopoint.py, txpipe/utils/patches.py
Saves the number of patches as metadata in the sacc file output when present.
Closes #176
=> Add number of patches to file metadata

examples/metadetect/config.yml, examples/metadetect/pipeline.yml, txpipe/twopoint_fourier.py, txpipe/utils/nmt_utils.py
This change extracts the bandpower values from namaster and saves them to sacc.
It also enables the Fourier stage in the continuous integration (just the metadetect pipeline) by dropping down to nside 64 so it runs in a reasonable amount of time.
=> Save bandpowers and enable Fourier stages in testing

examples/lensfit/config.yml, examples/lensfit/pipeline.yml, examples/redmagic/pipeline.yml, txpipe/__init__.py, txpipe/extensions/clmm/__init__.py, txpipe/extensions/clmm/rlens.py, txpipe/ingest_redmagic.py, txpipe/lens_selector.py, txpipe/random_cats.py, txpipe/twopoint.py, txpipe/utils/patches.py
The "metric" configuration option in TreeCorr was always automatically exposed in TXPipe, since you the config dict is passed on to the treecorr GGCorrelation (etc) initializers. So you can add metric to the config of any subclass and it will work.
This makes it an explicit option in the base class and prints it out.
=> Print out metric in TXTwoPoint

txpipe/extensions/twopoint_scia.py, txpipe/twopoint.py, txpipe/twopoint_null_tests.py
@marina-ricci spotted that zero-sized catalogs can cause a crash in the 2point stage. This change checks for them and returns None for their `Measurement.object` value. We then have to skip such values later on and not put them in the sacc.
@empEvil could you check that my changes here to your SCIA stage make sense?
=> Handle zero-size catalogs in 2pt stages

txpipe/auxiliary_maps.py, txpipe/blinding.py, txpipe/convergence.py, txpipe/covariance.py, txpipe/exposure_info.py, txpipe/input_cats.py, txpipe/jackknife.py, txpipe/map_correlations.py, txpipe/map_plots.py, txpipe/maps.py, txpipe/masks.py, txpipe/metacal_gcr_input.py, txpipe/metadata.py, txpipe/photoz_mlz.py, txpipe/photoz_stack.py, txpipe/psf_diagnostics.py, txpipe/theory.py, txpipe/twopoint_plots.py
Addresses issue #250 .
Also renames some classes which did not match their name attribute
=> Label non-parallel stages as such

examples/metadetect/config.yml, examples/metadetect/pipeline.yml, txpipe/covariance.py
This implements the interface with TJPCov to compute the SSC. Now, the stage `TXFourierTJPCovariance` outputs not only `summary_statistics.sacc` but also `summary_statistics_gauss.sacc` and `summary_statistics_ssc.sacc` if they are requested. In order to compute both the Gaussian and the SSC terms, one has to define in the corresponding stage configuration in `config.yml` the following variable `cov_type = ['gauss', 'ssc']`.
The SSC implementation in TJPCov is at the moment under review (https://github.com/LSSTDESC/TJPCov/pull/34), so it might contain some bug.
=> Implemented TJPCov SSC 

examples/metadetect/config.yml
Updated TJPCov version where the lmax issue is fixed (PR https://github.com/LSSTDESC/TJPCov/pull/43). (And updated the config example file to test for it).
=> nmtCov: fixed lmax

.github/workflows/ci_nersc.yml, .gitlab-ci.yml
This uses the instructions in https://desc-continuous-integration.readthedocs.io/en/latest/desc/ci_at_nersc.html to try to run a CI test at NERSC.
=> Add Continuous Integration running on Nersc

examples/2.2i/pipeline.yml, examples/cosmodc2/pipeline.yml, examples/lensfit/pipeline.yml, examples/redmagic/pipeline.yml, examples/skysim/pipeline.yml, txpipe/lens_selector.py, txpipe/utils/hdf_tools.py
We have some splitter classes which take a catalog and split it by tomographic bin so that TreeCorr can read it more easily. Currently we have a subclass which also adds radial comoving distances for use in cluster work or other analyses apart from the 3x2pt case.
This change simplifies by merging the 3D splitters into the 2D, so that we always include a fiducial estimate of the comoving distances in the split treecorr files.
Addresses issue #248
=> Remove the 3D splitter classes 

examples/metadetect/config.yml, txpipe/covariance.py
Updated to the latest version of TJPCov. I have checked that the covariance of the Gaussian sims is recovered by this new version (also the SSC). The plot below shows the logarithmic absolute magnitude relative difference between the new and old NaMaster Gaussian covariance for the Gaussian sims with nside 4096.
```
max abs rdev diag 5.073366493579812e-07
max abs rdev 1-off diag 0.00029870120325070637
max abs rdev 2-off diag 1.4045054967715132e-05
max abs rdev 0.1497571259501531
number of elements with abs rdev > 1e-3 42
Compare chi2
10889.579466013645
10889.579788057401
```
I have also checked that the refactored `wigner_transform.py` does not break the Real space covariance:
```
xi diff 2.458415715353579e-06
max abs rdev diag 3.0167256048763136e-07
max abs rdev 1-off diag …
```
=> Tjpcov update

.gitmodules, conda.txt, examples/2.2i/pipeline.yml, examples/2.2i/pipeline_1tract.yml, examples/cosmodc2/pipeline.yml, examples/cosmodc2/pipeline_redmagic.yml, examples/cosmodc2/pipeline_redmagic_full.yml, examples/cosmodc2/pipeline_redmagic_no_shape_noise.yml, examples/cosmodc2/pipeline_redmagic_no_shape_noise_full.yml, examples/gaussian_sims/pipeline_gaussian_sims.yml, examples/lensfit/pipeline.yml, examples/metacal/pipeline.yml, examples/metadetect/pipeline.yml, examples/randoms/pipeline_randomsonly.yml, examples/redmagic/pipeline.yml, examples/redmagic/pipeline_complete.yml, examples/skysim/pipeline.yml, examples/star-challenge/sample-for-pz_full.yml, requirements.txt, txpipe/covariance.py, txpipe/covariance_nmt.py, txpipe/mapping/basic_maps.py, txpipe/random_cats.py
I have removed the `submodules/TJPCov` dependency and used the pypi version of TJPCov. I have also modified a few imports that will be broken in tjpcov-0.1.2 (i.e. after merging https://github.com/LSSTDESC/TJPCov/pull/62). The new way is compatible with current version of TJPCov, too.
Edit: extra commits replacing `np.bool` by `bool` and `np.float` by `float` have been pushed to avoid the tests failing due to numpy deprecations. Would have it been better to change `np.float` to `np.float64`?
=> Use the pypi version of TJPCov

txpipe/extensions/clmm/rlens.py, txpipe/extensions/twopoint_scia.py, txpipe/random_cats.py, txpipe/twopoint.py, txpipe/twopoint_null_tests.py
- added stage to randomly subsample the binned randoms catalog and save as separate file
- added config option to twopoint to use the subsampled catalog for the RR clustering term
tested on cosmodc2 example. Speeds up the auto correlations by 30% and cross correlations by 50% (will do better for larger random/data ratios) and negligible change in correlation function
=> Subsample randoms savecat

txpipe/maps.py
1. Changed how delta_g is calculated.
2. Added option to exclude from the delta_g calculation any pixels whose values are below a user-specified threshold ("weight_thresh" in the config) in the mask .
=> TXDensityMaps modifications

examples/desy3/config.yml, examples/desy3/pipeline.yml, txpipe/source_selector.py, txpipe/utils/calibration_tools.py
This pull request fixes issues with the selection part of the DES-Y3 metacal response.
It also adds the option of using the diagonal approximation R==(R[0,0]+R[1,1])/2 (as used in DES-Y3).
The output responses have been cross-checked against the official calibration code and also table 4 of 2105.13541.
=> metacal fix

.github/workflows/ci.yml
changing mac OS version in CI installation test
macos-latest now defaults to M1 which TXPipe does not yet officially support. Previously macos-latest pointed to macos-12 so fixing to that temporarily until we can get M1 installation set up
=> change macos version in CI

txpipe/utils/patches.py
There is a hang in TXTwoPoint when only a single object is found in a patch. This fixes that.
=> Avoid hang when a single object found in first file when making patches

txpipe/diagnostics.py, txpipe/mapping/basic_maps.py, txpipe/mapping/dr1.py, txpipe/psf_diagnostics.py, txpipe/utils/calibration_tools.py, txpipe/utils/number_density_stats.py
This stops you from needing parallel_statistics in the launching environment, which is needed to use the lsst environment to do ingestion at NERSC.
Some older imports were not needed at all.
=> Move parallel statistics imports inside functions

bin/environment-perlmutter.yml
I found the perlmutter install wasn't working because of a missing git+ in the install yml file. This PR just adds it
=> added git to dataregistry pip install at nersc
